### PR TITLE
new DPU: e-SparqlEndpoint

### PR DESCRIPTION
**Pull request by skodape**
New DPU according to #178.

There are several major issues remaining to solve, before pull request can be merged:
1) SK Localization
2) Runtime dependencies ?
There is a section of dependencies in a readme file, is that enough?
We can add links to maven repository, or something like that? Unfortunately there is, best to my knowledge, no unified system of dependency handling-providing introduced in UV.

@tomas-knap: How should we handle such situations?

### CODE REVIEW

**Comment by skrchnavy** [comment]
Version and parent version shall be synchronized with #232

**Comment by skrchnavy** [comment]
Be aware when merging this pull request, branch was not created based on gitflow but was created from branch dpu/t-rdfToFiles_2.1.0 (it is opened as pull request #216).
So prior to approve this pull request, #216 have to be approved. If #216 rejected then also this PR #222 have to be rejected.

I propose to create new feature branch and cherry pich the changes related to this new DPU and then we can close this pull request without merging.

**Comment by tomas-knap** [comment]
I added jackson-core, jackson-annotations, jackson-databind dependencies. Nevertheless, when I try to use the DPU (I put the DPU on the canvas and try to extract one triple from dbpedia.org/sparql) I got: 

```
Execution failed because: DPU.innerExecute throws throwable.eu.unifiedviews.dpu.DPUException: DPU.innerExecute throws throwable.
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:125)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of org/eclipse/osgi/internal/baseadaptor/DefaultClassLoader) previously initiated loading for a different type with name "org/openrdf/repository/RepositoryConnection"
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:196)
... 
```

**Comment by skrchnavy** [comment]
@eea03 please add SK localization.

**Comment by skodape** [comment]
Will be recreated from current develop.

**Pull request closed without merging**
