### PR TITLE
T-Unzipper: Update documentation and description

### PR DESCRIPTION
**Pull request by mbl-eea-sk**
Update of documentation and checkbox description in t-unzipper regarding @eea04 notices
To unify:
* `about.md`: If checked DPU prevents collision in names of files send on output when multiple zip files with the same/similar structure are unzipped.<br>Uncheck sends on output files names as are in zip files.<br>If not sure keep checked
* `about_sk.md`: Ak je zaškrtnuté, je pred názov súboru z archívu pridaný náhodný reťazec, čím sa predíde duplicitným názvom v procese v prípade, že by existoval v procese nejaký iný súbor s rovnakým menom.
* `resources.properties`: If checked then output symbolic names of output files are prefixed with symbolic name of unzipped file. Check to prevent symbolic names collision if multiple zip files with same structure are unzipped. If you do not know, then check this.
* `resources_sk.properties`: Ak zaškrtnuté, potom symbolické názvy výstupných súborov budú mať predponu symbolického názvu rozbaleného súboru. Zaškrtnite, aby ste zabránili kolízií symbolického mena, v prípade ak je rozbalených viacero súborov s rovnakou štruktúrou. V prípade ak ste si nie istý, zaškrtnite toto políčko.

### CODE REVIEW

**Comment by eea04** [comment]
Incomplete, read the instructions again.

**Comment by mbl-eea-sk** [comment]
Well, missing example or did I overlook something else?

**Comment by eea04** [comment]
Based on current doc, user is *unable* to know what the names (or is it symbolic names? or virtual paths?) of unzipped files will be. The user then publishes the files under these symbolic names (virtual paths), so it is important to know exactly what the unzipper does to the names (symbolic names? virtual paths?)
And yes, even if the description were precise (which it currently isn't), without examples, only DPU developers, and only some of them, would ever be able to understand what this magnificent DPU is doing. So let's do examples.

**Comment by mbl-eea-sk** [comment]
@tomas-knap can you please support this task with exact definitions of expresses *virtual path*, *symbolic name* and eventual other ones related?

**Comment by tomas-knap** [comment]
symbolic name = identifier of the entry (file, rdf graph) in the data unit. This identifier may change as the file is being processed by the pipeline. 
virtualPath = path under which the given entry (in this case only file) should be stored when it is loaded outside of UnifiedViews to some target server. So if virtual path is e.g. x/y/data.ttl, and loader loads the data to target folder F, the file should be automatically placed to F/x/y/data.ttl.

In most cases when working with files, symbolic name = virtualPath.

In the user documentation, I would suggest to talk just about file name, zip file name etc., so to describe it as Michal suggested in https://team.eea.sk/jira/browse/EDEM-204.

I will prepare precise definition of these terms and their usage for DPU developers.

**Comment by eea04** [comment]
Only talking about filename would of course be nice, but *what is filename* in UV? Is it symbolic name? Or part of virtual path? Or yet something else?

We should simplify the documentation, but not to the point of user not being able to know what the DPU actually does. I had to literally experiment with this DPU to find out how it names the extracted files and still I wasn't sure I understood the general algorithm.

**Comment by tomas-knap** [comment]
I added explanation of symbolicName/virtualPath to https://grips.semantic-web.at/display/UDDOC/Basic+Concepts+for+DPU+developers

**Comment by tomas-knap** [comment]
I slighly updated EN doc (to better explain unchecked variant). If you think it will help, you may also adjust SK version. Approved.

**Pull request merged**
