### PR TITLE
E-FilesDownload: Added hash to URI string.

### LINKED ISSUE #274: e-filesDownload: duplicate symbolic names generated
e-filesDownload generates symbolic names from URL's path. The path is often non-unique, which results in an error. For example, there are cases in which downloaded resources are distinguished by query string. Consider downloading resources from the following URLs:

* <http://www.health.gov.sk/Zdroje?/Sources/datasety/1722/1722--kurz-PP-ku-dnu-31-10-2013/Health-1722-ku-dnu-31-10-2013.xml>
* <http://www.health.gov.sk/Zdroje?/Sources/datasety/1722/1722--kurz-PP-ku-dnu-30-09-2013/Health-1722-ku-dnu-30-09-2013.xml>

Doing so in a single instance of e-filesDownload results in an error `Duplicate entry found for symbolic name: /Zdroje`.

The method of generating symbolic names should be improved. Instead of just the URL's path, it should take into account the whole URL (e.g., by using its SHA1 hash).

I marked this as an enhancement, because it can be avoided by explicitly setting file names of the downloaded resources.

Context: I discovered this issue in e-filesDownload version 2.1.0.

### PR DESCRIPTION
**Pull request by mbl-eea-sk**
File name now includes hashed URI to avoid conflicts when downloading more different files with the same name (resolves #274).

### CODE REVIEW

**Comment by tomas-knap** [comment]
The problem of the proposed approach is that the filename (symbolic name and virtual path) is than always meaningless and cannot be used as the file is filtered, renamed in further DPUs on the pipeline. Thus I propose slightly different approach: 

1) If the entry to be downloaded has file name explicitly specified in the config dialog of the DPU, then such filename is used as name of the file. (this is the same as it worked before)
2) otherwise, when there is no explicit filename in the configuration of the DPU, lets use hashed file URI specified in the config dialog which is always available. 

So the result may look like the following (first file had explicitly specified filename, the rest of them did not have explicitly specified filename): 

screen shot 2015-08-11 at 15 45 29

**Comment by tomas-knap** [comment]
Waiting for feedback from @skodape if it is ok for CUNI

**Comment by tomas-knap** [comment]
It is OK also for CUNI. Prepared for merging.

**Comment by tomas-knap** [comment]
One comment before we can merge: Why did you use deprecated method shaHex? 
https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/digest/DigestUtils.html#shaHex(byte[])

Can we use sha1Hex instead?

**Comment by mkl-eea-sk** [comment]
Looking forward for users, who will benefit from seeing hash :-)

Even Windows 95 was able to name conflicting files this way:
1. zmluvy.doc
2. zmluvy.doc(1)
etc

**Comment by mbl-eea-sk** [comment]
Have changed it but this also required to update pom.xml dependencies. The default *commons-codec* version 1.2 did not recognize shaHex() as deprecated and sha1Hex() was undefined there. Now it works.

**Comment by tomas-knap** [comment]
@mkl-eea-sk User may always specify the filename manually if he needs to work with the filename later on the pipeline or needs to use better name for the VirtualPath. If the user just needs to iterate over files, the name is not important for him. I will update a bit readme in order to clarify importance of specifying filename in the conf dialog of the DPU.

**Pull request merged**
