### PR TITLE
Bugfixing wrong artifactId e-sparqlEndpoint -> uv-e-sparqlEnpoint

### PR DESCRIPTION
**Pull request by mkl-eea-sk**
Bugfixing wrong artifactId e-sparqlEndpoint -> uv-e-sparqlEnpoint

### CODE REVIEW

**Comment by tomas-knap** [comment]
Downside is that if some instance is already using this DPU on some pipelines, it cannot be easily migrated to this version when new versions of e-sparqlEndpoint becomes available and modification of the database is needed and target/dpu is needed. 

I added such info to README/CHANGELOG

**Comment by skrchnavy** [comment]
Shall be also reflected in debian installation to properly replace older version of DPU.

**Comment by mkl-eea-sk** [comment]
@skrchnavy  Was this DPU released already ? With wrong artifactId? I was thinking it was not released, so we can fix the issue prior first public release.

**Comment by skrchnavy** [comment]
DPU released in 2.1.1 (https://github.com/UnifiedViews/Plugins/tree/UV_Plugins_v2.1.1)
Was not included into debian installation (reported as #312)

**Pull request merged**
