### PR TITLE
Java Package names for DPUs changed to eu.unifiedviews space. Resolve #181

### LINKED ISSUE #181: Java package name shall be eu.unifiedviews.plugins.* for DPUs
Currently thease DPUs are in package cz.cuni.mff.xrg.uv.*
* t-sparqlConstruct
* t-sparqlUpdate
* t-tabular
* t-xslt

They shall be migraterd to eu.unifiedviews.plugins.*

### PR DESCRIPTION
**Pull request by mbl-eea-sk**
Classes moved to correct packages except Configuration classes.
solves #181

### CODE REVIEW

**Comment by mbl-eea-sk** [comment]
issue: https://github.com/UnifiedViews/Plugins/issues/181

**Comment by mkl-eea-sk** [comment]
connects #181

**Comment by tomas-knap** [comment]
Configuration classes must be also moved correctly. Do not forget that there are pipelines using t-xslt, where the configuration is stored as: 

```
<MasterConfigObject>
    <configurations>
      <entry>
        <string>dpu_config</string>
        <string>&lt;object-stream&gt;
  &lt;cz.cuni.mff.xrg.uv.transformer.xslt.XsltConfig__V2&gt;
    &lt;xsltTemplate&gt;&lt;/xsltTemplate&gt;
    &lt;xsltTemplateName&gt;Empty&lt;/xsltTemplateName&gt;
    &lt;failOnError&gt;false&lt;/failOnError&gt;
    &lt;outputFileExtension&gt;.ttl&lt;/outputFileExtension&gt;
    &lt;filesParameters class=&quot;linked-list&quot;/&gt;
    &lt;numberOfExtraThreads&gt;0&lt;/numberOfExtraThreads&gt;
  &lt;/cz.cuni.mff.xrg.uv.transformer.xslt.XsltConfig__V2&gt;
&lt;/object-stream&gt;</string>
      </entry>
      <entry>
        <string>addon/faultToleranceWrap</string>
        <string>&lt;object-stream&gt;
  &lt;eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance_-Configuration__V1&gt;
    &lt;enabled&gt;true&lt;/enabled&gt;
    &lt;exceptionNames class=&quot;linked-list&quot;/&gt;
    &lt;maxRetryCount&gt;-1&lt;/maxRetryCount&gt;
  &lt;/eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance_-Configuration__V1&gt;
&lt;/object-stream&gt;</string>
      </entry>
    </configurations>
  </MasterConfigObject>
```

So you must ensure that after updating the package names, the outdates configuration can be loaded properly.

**Comment by tomas-knap** [comment]
From my point of view, this issue has low prio

**Comment by skrchnavy** [comment]
this is first step in migration, configuration was not moved, keeps original package name.

**Comment by mkl-eea-sk** [comment]
Yes, I have taken the decision to not move configuration files from their original package names.
Also t-xslt is a nightmare DPU, which has the configuration as Composite classes from different packages. I would appreciate if author of this design could also teach us, how to write a Configuration Migration class for such Configuration classes design. It will also prove that the design of configuration upgrade is good and usable. I am unable to figure out (in reasonable time) how to upgrade such multiclass,multipackage configuration.

**Comment by skrchnavy** [comment]
@mkl-eea-sk please merge develop into this branch and resolve conflicts if any.

**Comment by mkl-eea-sk** [comment]
Merged develop to feature/BadPackages. No conflicts.

**Pull request merged**
