### PR TITLE
e-filesDownload: Layout Changes

### LINKED ISSUE #339: Wasteful use of screen space in e-filesDownload configuration dialog
Similarly to #289 the configuration dialog of e-filesDownload wastes a lot of screen space, so that its key part is hard to navigate on smaller screens (e.g., 13.3" laptops).

screen shot 2015-09-14 at 13 41 42

Only 2 and a half rows of the table of downloaded files are visible. There is a lot of space waster by block level controls that can be inlined.

### PR DESCRIPTION
**Pull request by mbl-eea-sk**
- table with files to download size set back to maximum
- configuration inputs fit into a single line
- resolves #339

### CODE REVIEW

**Comment by eea03** [comment]
There was a reason to set table height to fixed height.
DPU dialog size is now dynamic based on actual size of application window.
This means on small screens, setSizeFull() causes that table will be very small (e.g. I did not have even one row displayed in table.) 
Thus table height should be fixed to be able show e.g. 4 table rows

**Comment by mbl-eea-sk** [comment]
@jindrichmynarz which version do you prefer?

**Comment by jindrichmynarz** [comment]
It is quite difficult to imagine how it would look like. Can you share screenshots of the two versions on small screen?

**Comment by skrchnavy** [comment]
Isn't there possibility to setup minSize for some components?

**Comment by mbl-eea-sk** [comment]
I can view it only with screen resolution decreased to 800x600. Then it appears:
set to full size (needs to scroll to find the configuration inputs below):
fullsize
set to fixed size:
hardsize

**Comment by jindrichmynarz** [comment]
Screenshot of the first layout looks better. I would avoid additional horizontal and vertical scrollbars if possible.

**Comment by mbl-eea-sk** [comment]
Well, that's the currently committed solution.

**Comment by mbl-eea-sk** [comment]
@skrchnavy there is not on Java level (by setting property in code).

**Comment by jindrichmynarz** [comment]
An idea: Can you fit the plus button into the first column of the first row in the table?

**Comment by mbl-eea-sk** [comment]
I have googled something about this but it appears not to be possible yet, even with currently used tools.
http://stackoverflow.com/questions/27375745/put-a-component-in-a-table-column-header

**Comment by skrchnavy** [comment]
What about to add the [+] under the table? And if possible to catch '+' key press as a shortcut to the button.

**Comment by mbl-eea-sk** [comment]
The button does not listen on "+" key and it's ASCII code 43. Can we use INSERT key instead?
Another question - to move the button under the table will require to scroll down the empty table. On minor screens it may confuse the user when they cannot find it on the first sight. Consider this please.

**Comment by mbl-eea-sk** [comment]
@skrchnavy feed back please

**Comment by skrchnavy** [comment]
Insert is OK.
regarding bottom part of screen, when '+' button is not visible when empty table then the screen is too small. Please make screenshots with button under table (empty/few rows).

**Comment by mbl-eea-sk** [comment]
It does not depend on number of lines in the table, it's still too down.
down_button

**Comment by skrchnavy** [comment]
@eea04 please comment

**Comment by tomas-knap** [comment]
I suggest to keep the "+" button where it is, as it is more intuitive to have it above the table. 

In general, we should only avoid the following situation: 
screen shot 2015-09-22 at 09 37 26

So I suggest to specify certain minimal heigh of the table component, so that if there is less space in the dialog, vertical scrollbar appears for the whole configuraiton - roughly as follows:

screen shot 2015-09-22 at 09 39 00

Since this is the current solution as I understood from the comments above, I propose to mark this as "ready for test"

**Comment by skrchnavy** [comment]
@mbl-eea-sk  is there min value defined?

**Comment by mbl-eea-sk** [comment]
No as explained in https://github.com/UnifiedViews/Plugins/pull/343#issuecomment-140680706
This needs to be solved on CSS level or we should return back to the solution explained in https://github.com/UnifiedViews/Plugins/pull/343#issuecomment-140671668

**Comment by skrchnavy** [comment]
I understood that comments but isn't it possible to setup css style embeded in html code?
```html
<table style="min-height:100px;">
    ...
</table>
```

**Comment by mbl-eea-sk** [comment]
I don't have deep knowledges of Vaadin but I suppose that HTML is rendered from Java source code and all the <table> attributes are based on set* methods applied to Vaadin Table instance. So how to access and modify the HTML code?

**Pull request merged**
