### PR TITLE
Bug fix issue 395, bug fix JUnit test

### PR DESCRIPTION
**Pull request by loryzizu**
I think I found the bug for my issue #395 , it happens also with the provided Junit test (that has a bug itself)

### CODE REVIEW

**Comment by tomas-knap** [comment]
@hanecak Can you please test that?

**Comment by hanecak** [comment]
@tomas-knap I've tested it and it works as expected (i.e. I've tried few test with current DPU and observed lost row and then I've tries same with this fix applied and lose of row no longer occurs).

@loryzizu, thank you for the fix.

**Comment by hanecak** [comment]
Side observation: The call to 'TableToRdfConfigurator.configure()' quite complicates the code to the point of not-that-easy-to-understanding, requiring also 'rs.beforeFirst()'. Hopefully some refactor later on will simplify that.

**Comment by tomas-knap** [comment]
The code with rs.beforeFirst() is more elegant (imho), it does not repeat the body of the while cycle for processing rows. @loryzizu Many thanks!

**Comment by tomas-knap** [comment]
Merged to develop, the second commit reverted by: https://github.com/UnifiedViews/Plugins/commit/b419a087021a9a7ed32cadd29e33f4555e841aa6
(the version with rs.beforeFirst is nicer, no need to repeat the body of the while cycle for processing rows)

**Pull request merged**
