### PR TITLE
 T-RDFToFiles should log progress

### PR DESCRIPTION
**Pull request by skrchnavy**
fix of #80

### CODE REVIEW

**Comment by tomas-knap** [comment]
#97 does not solve #80. I would suggest to merge this pull request and postpone solution of #80 till time when more important issues are solved.

**Comment by mkl-eea-sk** [comment]
so merge it!

**Comment by skrchnavy** [comment]
@ AndreAga - please finish feature (feature/t-rdfToFiles)

**Comment by AndreAga** [comment]
@skrchnavy Done.

**Pull request merged**
