### PR TITLE
Slovak translations of t-tabular

### LINKED ISSUE #335: t-tabular: Documentation should be updated (doc/About)
There is plenty of config options in t-tabular, but they are not documented. See: 

https://github.com/UnifiedViews/Plugins/blob/develop/t-tabular/doc/About.md
https://github.com/UnifiedViews/Plugins/blob/develop/t-tabular/doc/About_sk.md

doc/About*.md should be updated.

### LINKED ISSUE #358: T-Tabular: missing SK translation
DPU uv-t-tabular is not translated to slovak (SK).

### PR DESCRIPTION
**Pull request by skrchnavy**
To finalize PullRequest #362 to add t-tabular translation
Resolved #358 
Resolves #335

### CODE REVIEW

**Comment by eea03** [comment]
Translation of T-Tabular DPU implementation finished and tested.
@skrchnavy or @tomas-knap please review and approve

**Comment by tomas-knap** [comment]
I will review by tomorrow

**Comment by tomas-knap** [comment]
The key dialog.mapping.advanced.description cannot be loaded properly and causes that the DPU cannot be imported to UV (EN version):

screen shot 2015-11-05 at 13 24 05

```
2015-11-05 13:22:06,818 [http-bio-8080-exec-9] ERROR cz.cuni.mff.xrg.odcs.frontend.gui.ViewComponent - Can't load DPU '50'
cz.cuni.mff.xrg.odcs.frontend.dpu.wrap.DPUWrapException: Failed to load dialog.
	at cz.cuni.mff.xrg.odcs.frontend.dpu.wrap.DPURecordWrap.getDialog(DPURecordWrap.java:123) ~[DPURecordWrap.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.buildDPUDetailLayout(DPUViewImpl.java:356) [DPUViewImpl.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl.selectNewDPU(DPUViewImpl.java:877) [DPUViewImpl.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl.dpuUploadedEventHandler(DPUPresenterImpl.java:349) [DPUPresenterImpl.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl$14.uploadSucceeded(DPUViewImpl.java:741) [DPUViewImpl$14.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.AuthAwareUploadSucceededWrapper.uploadSucceeded(AuthAwareUploadSucceededWrapper.java:64) [AuthAwareUploadSucceededWrapper.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_21]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:979) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.Upload.fireUploadSuccess(Upload.java:888) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.Upload$2.streamingFinished(Upload.java:1150) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:597) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.FileUploadHandler.handleFileUploadValidationAndData(FileUploadHandler.java:453) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.FileUploadHandler.doHandleSimpleMultipartFileUpload(FileUploadHandler.java:403) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:285) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [vaadin-server-7.3.7.jar:7.3.7]
	at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:123) [ODCSApplicationServlet.class:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.39]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.39]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.39]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.39]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.39]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.39]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947) [catalina.jar:7.0.39]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.39]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.39]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009) [tomcat-coyote.jar:7.0.39]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.39]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.39]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
Caused by: java.lang.IllegalArgumentException: can't parse argument number:  or 
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1420) ~[na:1.7.0_21]
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479) ~[na:1.7.0_21]
	at java.text.MessageFormat.<init>(MessageFormat.java:363) ~[na:1.7.0_21]
	at java.text.MessageFormat.format(MessageFormat.java:835) ~[na:1.7.0_21]
	at eu.unifiedviews.helpers.dpu.localization.Messages.getString(Messages.java:66) ~[uv-dpu-helpers-2.1.4.jar:na]
	at eu.unifiedviews.helpers.dpu.context.UserContext.tr(UserContext.java:68) ~[uv-dpu-helpers-2.1.4.jar:na]
	at eu.unifiedviews.plugins.transformer.tabular.TabularVaadinDialog.buildMainLayout(TabularVaadinDialog.java:373) ~[na:na]
	at eu.unifiedviews.plugins.transformer.tabular.TabularVaadinDialog.buildDialogLayout(TabularVaadinDialog.java:125) ~[na:na]
	at eu.unifiedviews.helpers.dpu.vaadin.dialog.AbstractDialog.initialize(AbstractDialog.java:108) ~[uv-dpu-helpers-2.1.4.jar:na]
	at cz.cuni.mff.xrg.odcs.frontend.dpu.wrap.DPURecordWrap.loadConfigDialog(DPURecordWrap.java:229) ~[DPURecordWrap.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.dpu.wrap.DPURecordWrap.getDialog(DPURecordWrap.java:119) ~[DPURecordWrap.class:na]
	... 39 common frames omitted
Caused by: java.lang.NumberFormatException: For input string: " or "
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.7.0_21]
	at java.lang.Integer.parseInt(Integer.java:481) ~[na:1.7.0_21]
	at java.lang.Integer.parseInt(Integer.java:527) ~[na:1.7.0_21]
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1418) ~[na:1.7.0_21]
	... 49 common frames omitted

```

**Comment by tomas-knap** [comment]
Please test that the DPU can be loaded properly for EN localization

**Comment by eea03** [comment]
Ok, I fixed the issue and tested DPU for both Slovak and English localization

**Pull request merged**
