### PR TITLE
L-filesToVirtuoso with rdf configuration

### PR DESCRIPTION
**Pull request by skodape**
Added RDF configuration for dataset-dependant fields.

warning: Hard-coded version of plugin DevEnv is used as parent class does no provide up to date dependency.

Requires https://github.com/UnifiedViews/Plugin-DevEnv/pull/44

### CODE REVIEW

**Comment by skrchnavy** [comment]
Version and parent version shall be synchronized with #232

**Comment by skrchnavy** [comment]
@skodape is this PR ready for test?

**Comment by tomas-knap** [comment]
The sample of the configuration is strange - 2nd 3rd triple should have literal as object?
screen shot 2015-06-23 at 15 55 05

**Comment by tomas-knap** [comment]
The version of the API used should be 2.1.0-SNAPSHOT

**Comment by skodape** [comment]
Will be recreated from current develop.

**Comment by skrchnavy** [comment]
@skodape version shall be 2.1.0 (not released yet so not necessary to upgrade version).

**Pull request closed without merging**
