### PR TITLE
new DPU: e-DistributionMetadata (CKAN Resource model, without DCAT in UV)

### PR DESCRIPTION
**Pull request by mkl-eea-sk**
Using only Resource Helper, without DCAT inside UV.

### CODE REVIEW

**Comment by jindrichmynarz** [comment]
Labels in the date pickers (e.g., "April") should follow the chosen localization. For example, the UnifiedViews instance at <http://192.168.7.136:8080/unifiedviews/> is configured with Slovak locale, but the date picker shows English labels.

Moreover, the date format should follow the locale as well. Currently, the format is the U.S. MM/DD/YY even if Slovak locale is used.

**Comment by jindrichmynarz** [comment]
The description field can use a textarea instead of text input to provide more space for longer description if necessary.

**Comment by jindrichmynarz** [comment]
Labels of fields should be consistent in using colon. For example, there's "Nadpis distribúcie" but "URL:". This should be consistent with labelling of fields other DPUs.

**Comment by mkl-eea-sk** [comment]
DatePicker format&locale: Vaadin uses the HTTP  Accept-Language for rendering DatePicker in locale the user has in its browser set. I have tested this behavior. Nevertheless, the locale may be forced programatically, so I have forced the locale to be the system wide locale (set in properties).
I had to localize the vaadin conversion error message manually.

Description is textarea.

Labels are with colon.

**Comment by mkl-eea-sk** [comment]
I have removed URL field as this is rewritten by every loader to CKAN we have (or inside CKAN itself). It is meaningless.

**Comment by tomas-knap** [comment]
One note: As the list of metadata was reduced, this e-distributionMetadata has most sense when   dumps are loaded to CKAN - in other cases - SPARQL Endpoint resources or REST API resources, it is not necessary to set up distribution title/description, mediaType does not make much sense, format can be set up automatically, so there is only issued, which may be also automatically computed?

So in case of SPARQL Endpoint/REST API resource, no e-distributionMetadata will be typically used (at least for now).

**Comment by mkl-eea-sk** [comment]
OMG, according to DCAT issued on distribution is 'date of first 
publication of given distribution (format)'. How this can be computed is 
kind of magic...
This field (issued) maps to Resource.created (according to POD mapping 
table 
https://project-open-data.cio.gov/v1.1/metadata-resources/#field-mappings)

**Pull request closed without merging**
