### PR TITLE
t-tabularToRelational default mapping

### LINKED ISSUE #304: t-tabularToRelational default mapping
t-tabularToRelational could use a default column mapping such as t-tabular does, so that table header is automatically converted to column names. Currently, the "mapping" only allows to specify columns that are used as parts of composite keys. For example, if I understood it correctly, it is not possible to rename columns (unless they are identified by their position in the input rather then their headers). Basically, a user has to copy the names of the columns from the input table.

Also note the "culumns" (=> "columns") and "CVS" (=> "CSV") typo in the [About.md](https://github.com/UnifiedViews/Plugins/blob/develop/t-tabularToRelational/doc/About.md). "Data begins at row" is one-offseted?

Context: latest commit from the develop branch (695e6a0e1580b7d8d4f896393210625541423a93).

### PR DESCRIPTION
**Pull request by mbl-eea-sk**
Typos mentioned in #304 updated.
Resolves #304

### CODE REVIEW

**Comment by skrchnavy** [comment]
@mbl-eea-sk any outstending work expected or could be reviewed?

**Comment by mbl-eea-sk** [comment]
Strange DPU for me (using H2 database functions). Several days I struggled to find solution so the mapping could do someone knowing it's architecture better.

**Comment by jindrichmynarz** [comment]
The documentation still does not explain whether "Data begins at row" is offset from 0 or 1.

**Comment by tomas-knap** [comment]
@eea02  Please finalize the documentation

**Comment by tomas-knap** [comment]
@eea02 The problem with default mappings was not solved yet

**Pull request closed without merging**
