### PR TITLE
l-filesToParliament: Added option to clear data before load

### PR DESCRIPTION
**Pull request by mkl-eea-sk**
Added option to clear data before load

### CODE REVIEW

**Comment by jindrichmynarz** [comment]
I compiled the DPU from 657a71c625e897250a079b8126c0629a15ebeab3 and the label of the dialog parameter for Parliament endpoint is "FilesToParliamentVaadinDialog.endpointURL". It probably should be something readable, such as "Parliament URL".

**Comment by mkl-eea-sk** [comment]
Fixed here https://github.com/UnifiedViews/Plugins/commit/164d66ab4a57deeb42c7fc67fd17ba781c69f929

**Comment by jindrichmynarz** [comment]
Tested, works as expected.

**Comment by tomas-knap** [comment]
Please update README (clear destination graph option), then can be merged

**Pull request closed without merging**
