### PR TITLE
t-filesFilter fix of #72

### PR DESCRIPTION
**Pull request by skrchnavy**
Changed some labels
Changed position of few elements in Vaadin dialog

### CODE REVIEW

**Comment by skrchnavy** [comment]
@tomas-knap to review

**Comment by skrchnavy** [comment]
@tomas-knap please provide feedback how to continue, automatic merge is not possible.

**Comment by skrchnavy** [comment]
@tomas-knap I checked why we can't merge automatically and there  is a conflict. with commit 5d47ecf9de58a6884d1c3b3322edec4c377b17eb

@skodape should check briefly if in this branch is anything useful and I propose to close this pull request without merge.

**Comment by tomas-knap** [comment]
It is not actual based on @skodape, closing

**Pull request closed without merging**
