### PR TITLE
New DPU T-RelationalToRdf

### PR DESCRIPTION
**Pull request by eea03**
New DPU is needed that can convert relational data to RDF.
This DPU is needed in eDemo to replace t-tabular DPU.

DPU implementation is based on t-tabular DPU, code was reused

### CODE REVIEW

**Comment by eea03** [comment]
I tested the DPU against T-Tabular DPUs with the same source data (both in CSV and in SQL) and DPUs provide the same results;
As far as I can say, it works as expected (the same as T-Tabular) 
However, I can't test all of its features as I don't understand them.

This DPU contains also localization and SK translations.

**Comment by tomas-knap** [comment]
Will review Wed 16./Thursday 17.

**Comment by tomas-knap** [comment]
Will review Wed 16./Thursday 17.

**Comment by tomas-knap** [comment]
I did not like that the t-tabular's logic is implemented twice - in t-tabular and also here. This increases maintenance costs. I think it would be much better if 

1) there will be a DPU, which converts relational (table) to file (CSV) and then the user can apply the standard t-tabular.
2) or the standard tabular would be extended to support also relational input data unit

The amount of redundant code is high in this case.  @eea04  Is there any special motivation for not following approach 1) or 2) ?

**Comment by eea04** [comment]
Currently we have the following DPUs implemented:
- csv to relational
- relational to rdf
- csv to rdf (t-tabular)

**Some points:**
- relational and RDF are two of the basic reference data types (the third one is file datatype).
- CSV is not a reference datatype; it's most closely a specific file representation of relational datatype.
- the first two DPUs perform translations between reference datatypes, the third does not
- without relational to rdf DPU, there is no way of converting relational data read from database to rdf.

As a sidenote, we do not intend to use t-tabular at all, as it's just a merge (one could argue useful shortcut) of two basic and necessary DPUs.

**Your points:**
1) Transforming relational data to CSV (we don't have this DPU, and I don't see it planned) and then CSV to RDF means using non-reference datatype as an intermediary and a bad one at that - CSV.
2) Wouldn't this DPU be too complicated? It might be argued that well manageable duplicity is better than complexity.
3) This would be a standard and the best solution from my point of view. Is this easily doable in UV infrastructure?

Using **R2RML**? Don't know the details, but high level: you will have two _different_ implementations of the _same thing_. The maintenance will be more complicated than having two nearly-duplicate implementations.

All in all, we need to deliver relational to rdf in _our project_ for reasons mentioned above. The best solution from my point of view is actually _implementing_ reuse between these DPUs, if it's doable.

**Comment by skrchnavy** [comment]
My point: we need this DPU very soon, if there is not any objections to approve, I suggest to release it as is now.
And I see also point 3 as best approach and it can be done in later phase (new issue to be created for library reuse).

**Comment by tomas-knap** [comment]
I prepared issue, which is about extracting common logic - https://github.com/UnifiedViews/Plugins/issues/345

**Pull request merged**
