### PR TITLE
Dpu/t files renamer 2.0.1 snapshot

### PR DESCRIPTION
**Pull request by skodape**
Bug fixes done in cooperation with @jindrichmynarz, also address issue #146

Note: You may consider localization of about.html.

### CODE REVIEW

**Comment by skrchnavy** [comment]
We can't break backward compatibility in DPU, so this must be changed back to support all configuration parameters that were defined. If there is a request for DPU that is not compatible, new DPU (new name have to be created).

**Comment by tomas-knap** [comment]
@skodape How is it with backward compatibility to the previou t-filesRenamer? Are there any config options in the previou t-filesRenamer which are not supported in t-filesRenamer 2.0?

**Comment by jindrichmynarz** [comment]
The interface of the 2.x DPU is completely different than the 1.x one. It's not backwards-compatible. However, this pull request does not create these breaking changes, it only fixes some issues that were already introduced in the DPU (in b992d1366000617375b72575efad7a1ae55c0cc0).

The solution could be to rename this DPU as @skrchnavy suggests, but then we would also need to revert to the previous version of the DPU, align it with the new helpers and fix its issues separately.

**Comment by skrchnavy** [comment]
I agree that this is not the pull request that shall be reverted. The code was merged in this commit: 28b1ff74d8fac0168ddce50bd3029f6d093b5c4f
where you can see there is also huge refactoring done and refused changes done in for example RenamerConfig_V2.

**Comment by hanecak** [comment]
Minor issue: Please specify in the README, that SPARQL REPLACE is essentially "regular expression".

Many people recognize term "regular expression", many people would even correctly recognize examples given in about.html as such. But few would deduce that from seeing "SPARQL REPLACE" in the README.

**Pull request merged**
