### PR TITLE
t-rdfToFiles: simplification of configuration

### PR DESCRIPTION
**Pull request by skodape**
Simplification of configuration class. Added RDF configuration. 

warning: Hard-coded version of plugin DevEnv is used as parent class does no provide up to date dependency.

Requires https://github.com/UnifiedViews/Plugin-DevEnv/pull/44

### CODE REVIEW

**Comment by skrchnavy** [comment]
be aware of conflicts with #232 in version of DPU, Readme.md and pom.xml have to be manually merged as version 2.1.0 (latest release was 2.0.1)

**Comment by skrchnavy** [comment]
@skodape is this PR ready for test?

**Comment by skrchnavy** [comment]
@skodape please merge features of 2.0.2 and 2.1.0 in Readme.md into one version (2.1.0). _2.0.2_ is not planed to be released.

**Comment by tomas-knap** [comment]
The version of the API used should be 2.1.0-SNAPSHOT

**Comment by skrchnavy** [comment]
please merge develop into this branch prior to finish feature.

**Comment by skodape** [comment]
Will be recreated from current develop.

**Pull request closed without merging**
