### PR TITLE
New relational DPUs

### PR DESCRIPTION
**Pull request by eea03**

### CODE REVIEW

**Comment by skrchnavy** [comment]
Dependency on UnifiedViews/Core/#287

**Comment by tomas-knap** [comment]
1 important issue: The general philosophy of UV so far is, that DPU developer cannot influence the physical location of the internal files, graphs -- UV manages its internal stores. As a result, such approach should be similar in relational data unit and DPU developer should NOT be able to set the target table name (currently, there is a configuration option for extractor and transformer, which allows to set up the target table name). Target table name is ok for loader, but not for extractor/transformer, where the target table is given by the data flow in the pipeline.  

The advantage of letting the system to manage the internal store (working database), e.g., managing the names of the tables, is that 
1) it is ensured that no name collision appears, pipeline designer do not need to think about that and may assume that fresh internal tables are available in each pipeline execution. As a result, it will not happen that pipeline designer by accident forget to clear the table for the next execution. It will also not happen that he specifies by accident wrong table name
2) DPU developer/pipeline designer cannot shortcut data flow by directly specifying name of the table he would like to work with without edge on the canvas. 
3) hiding the internal implementation, which allows easier changes in the future

Furthermore, current implementation will not work if certain pipeline is launched twice. THis may happen when one run was cancelled (and it is being destroyed) and next should be executed. Furthermore, if I want to debug the pipeline and then debug again and compare the results - I cannot do that without the need to change the table name in the configurations in all relational DPUs along the pipeline which is boring. 

Suggested solution: Extractors and Transformers do allow to specify label for the outputted table, but this is just a label, alias, the actual table name is prepared by the engine e.g. as "{ExecutionID}-{alias}".


Otherwise the DPUs are ok.

**Comment by eea03** [comment]
I absolutely agree with you that this is not a good approach and all the points you made are valid.
But this was agreed as quick & dirty solution also with @skrchnavy because otherwise, without building some GUI and operation specific transformers (e.g. JOIN, FILTER, RENAME, etc.) we could not see any possibility to implement this relational transformer. 

The solution you propose, would not solve this problem because transformer is implemented as SQL query executor. If user did not know the table name, he cannot write SQL query. If he provided this label, we could replace it under the hood with the real table name but this would require parsing of the SQL query and that is something we wanted to avoid. Note that these can be quite long and complex queries (JOINs, etc.)

And just one note: I thnk pipeline can be launched twice as this internal database is created per pipeline run in exec directory so the run should be independent.

But otherwise I agree but I cannot see a quick solution to this problem till release 2

**Comment by tomas-knap** [comment]
Since it is an extra feature, other may use, but they are not forced to,  I can approve merge of such code, but please supplement the extractor and loader with this warning (basically with two last comments - mine and yours) because I guess there is no time to improve it now.

**Comment by tomas-knap** [comment]
Approved, but with the warning, which must be added to the code of extractor and transformer

**Comment by skrchnavy** [comment]
@tomas-knap we discussed (as was mentioned) this approach and benefits. Current solution is compromise approach and if we use storage per pipeline then also safe.
Further discussion needed to solve transformation of 'table name' to 'real table name' to allow users to write proper queries (or to limit query types). Support is in interface, only implementation is not finalized.

**Comment by skrchnavy** [comment]
@eea03  : all relational DPUs shall have version 0.9.0-SNAPSHOT in develop branch due to the fact, there are expected changes.

**Pull request merged**
