### PR TITLE
Resolve #179

### LINKED ISSUE #179: l-filesToVirtuoso: Issue #176 should be properly solved
When finishing release UV 2.0, there was a bug https://github.com/UnifiedViews/Plugins/issues/176 in 
l-filesToVirtuoso. There was no time to fix it properly, so we just add possibility to turn off problematic section by using global properties, see https://github.com/UnifiedViews/Plugins/commit/71d2dd815acaa1411687d53c49de399ac5bf78e8

Solution: Solve the bug #176 properly.

### PR DESCRIPTION
**Pull request by mkl-eea-sk**

### CODE REVIEW

**Comment by mkl-eea-sk** [comment]
see this https://github.com/UnifiedViews/Plugins/issues/179

**Comment by skrchnavy** [comment]
@mkl-eea-sk are you sure it fixes #179 ?

**Comment by mkl-eea-sk** [comment]
Absolutely sure.

**Comment by mkl-eea-sk** [comment]
this requirement has been dropped

**Pull request closed without merging**
