### PR TITLE
new DPU: e-DistributionMetadata (DCAT Distribution model)

### LINKED ISSUE #237: Create new DPU: e-DistributionMetadata
Take this dpu https://github.com/mff-uk/DPUs/tree/master/dpu/e-distributionMetadata
move it here, rewrite it completely and make it work.

### PR DESCRIPTION
**Pull request by mkl-eea-sk**
Resolves #237

### CODE REVIEW

**Comment by tomas-knap** [comment]
The problem of the dialog (see below screenshot) is:
1) Because fields are autogenerated, they do not have anyhow logical order, a) title is almost at the end, not followed by description; b) format followed by mimeType,...  Also there are no logical spaces between relating metadata etc. 
2) It does not say which metadata must be filled for which type of CKAN resource - file dumps, SPARQL endpoint, REST API. Proposal: There should be at least some switch at the beginning (dump/sparqlEndpoint/REST), which, when selected, disables certain not-relevant fields. (mimeType hidden for sparql endpoint CKAN resources, ...) Also there should be some basic logic which helps/guides the user (format automatically prefilled for sparql endpoint CKAN resources; format hidden in case of dump, as format should be set to the same value as mimeType; format automatically prefilled for sparql endpoint CKAN resources ...)
3) there must be for sure documentation - as we won't have any wizards, any persone (e.g. distribution metadata manager) must be able to fill the metadata - this relates to 1) and 2) and may be covered in README/user doc, but must be covered. 

@skrchnavy Do we have time to address at least 1) + 2) before release? 

screen shot 2015-06-11 at 11 32 40

**Comment by mkl-eea-sk** [comment]
1) it is not because of autogeneration of fields. It is ordered as you 
specified in internal wiki :) take a look there :).  Nevermind, tell me 
desired ordering and I will reorder the fields. It is not a problem.
2) Yes, this is not according to specs, I was hoping to release 
'something' and then do this work later. It is upon you and @skrchnavy 
to decide if I will implement also this funcionality (5th column in 
internal wiki specification).
3) I tried to provide proper README.md, I would appreciate if you could 
also provide translation of fields (see localization of this DPU) as I 
was unable to make proper decisions there.

Conclusion:
1) easy - tell me ordering
2) I may start working, should be done until Monday.
3) I do not know what more can I do.

**Comment by tomas-knap** [comment]
Have a meeting, will provide intput to 1) later in the afternoon

**Comment by mkl-eea-sk** [comment]
closing and not merging

**Comment by skrchnavy** [comment]
branch deleted, can be restored

**Pull request closed without merging**
